version: '2'
services:
  iotex:
    container_name: iotex
    image: iotex/iotex-core:v1.6.1-rc2
    restart: unless-stopped
    ports:
      - 18080:8080
      - 4689:4689
      - 14014:14014
    volumes:
      - "$IOTEX_HOME/data:/var/data"
      - "$IOTEX_HOME/log:/var/log"
      - "$IOTEX_HOME/etc/standalone-config.yaml:/etc/iotex/config.yaml"
      - "$IOTEX_HOME/etc/standalone-genesis.yaml:/etc/iotex/genesis.yaml"
    command: iotex-server -config-path=/etc/iotex/config.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway

  redis:
    image: "redis:6.2.4-alpine3.14"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ../app_data/redis_data/:/data/
    restart: on-failure

  babel:
    container_name: babel-api
    image: iotexdev/babel-api:v1.0
    depends_on:
      - iotex
    ports:
      - "8545:8545"
    environment:
      - PORT=8545
      - CHAIN_ID=4690
      - END_POINT=http://iotx:14014
      - REDIS_HOST=redis
    command: npm start
