version: '3.1'

# networks:
#   frontend:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/24

services:
  iotex:
    container_name: iotex-core
    image: iotex/iotex-core:v1.6.1-rc2
    restart: on-failure
    ports:
      - 8080:8080
      - 4689:4689
      - 14014:14014
    volumes:
      - "$IOTEX_HOME/data:/var/data"
      - "$IOTEX_HOME/log:/var/log"
      - "$IOTEX_HOME/etc/standalone-config.yaml:/etc/iotex/config.yaml"
      - "$IOTEX_HOME/etc/standalone-genesis.yaml:/etc/iotex/genesis.yaml"
    command: iotex-server -config-path=/etc/iotex/config.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway

  redis:
    container_name: redis
    image: "redis:6.2.4-alpine3.14"
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ../app_data/redis_data/:/data/
    
  babel:
    container_name: babel-api
    build: 
        context: ./repos/IoTeX/babel-api
        dockerfile: Dockerfile
    depends_on:
      - iotex
    ports:
      - 8545:8545
    environment:
      - PORT=8545
      - CHAIN_ID=4690
      - END_POINT=http://iotx:14014
      - REDIS_HOST=redis
    command: npm start

  mysql:
    container_name: mysql
    image: mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: analytics
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  analytics:
    container_name: analytics
    build: 
        context: ./repos/IoTeX/iotex-analytics
        dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - iotex
      - mysql
    ports:
      - 8089:8089
    environment:
      - CONFIG=/etc/iotex/config.yaml
      - CHAIN_ENDPOINT=gateway.iotexlab.io:14014
      - ELECTION_ENDPOINT=35.185.52.92:8089
      - CONNECTION_STRING=root:example@tcp(mysql:3306)/
      - DB_NAME=analytics
    command: iotex-server

  
