version: '2'

services:
  jrpc:
    container_name: jrpc-linux-buildsystem
    image: jrpc-linux-buildsystem:latest
    # build: 
    #     context: ../
    #     dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - "$JRPC:/JRPC"
    command: bash -c "cmake .. && make"
