version: '2'

services:
  iotex:
    container_name: iotex-core
    image: iotex/iotex-core:$JRPC_version
    restart: on-failure
    ports:
      - 8080:8080
      - 4689:4689
      - 14014:14014
      - 15014:15014
    volumes:
      - "$JRPC/data/Mainnet/IoTeX:/var/data"
      - "$JRPC/log/Mainnet/IoTeX:/var/log"
      - "$JRPC/etc/Mainnet/IoTeX/config-override.yaml:/etc/iotex/config.yaml"
      - "$JRPC/etc/Mainnet/IoTeX/genesis-override.yaml:/etc/iotex/genesis.yaml"
    command: iotex-server -config-path=/etc/iotex/config.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway